# ref : https://github.com/ScoopInstaller/GithubActions
on:
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@6
        with:
          fetch-depth: 0
      - name: Excavator
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
          THROW_ERROR: "0"
